In [10]:
import numpy as np
import pandas as pd

data ={
    "ID": [1,2,3,4,2,5],
    "Name":["Ali","John","Sara",None,"John","David"],
    "Age":[25,np.nan,22,30,np.nan,28],
    "Salary":[50000,60000,None,70000,60000,80000],
    "Department":["HR","IT","HR","Finance","IT",None]
}
df =pd.DataFrame(data)
df

   ID   Name   Age   Salary Department
0   1    Ali  25.0  50000.0         HR
1   2   John   NaN  60000.0         IT
2   3   Sara  22.0      NaN         HR
3   4    NaN  30.0  70000.0    Finance
4   2   John   NaN  60000.0         IT
5   5  David  28.0  80000.0        NaN

In [3]:
df.isna()

      ID   Name    Age  Salary  Department
0  False  False  False   False       False
1  False  False   True   False       False
2  False  False  False    True       False
3  False   True  False   False       False
4  False  False   True   False       False
5  False  False  False   False        True

In [4]:
df.isna().sum()

ID            0
Name          1
Age           2
Salary        1
Department    1
dtype: int64

In [5]:
df=df.dropna()

In [6]:
df

   ID Name   Age   Salary Department
0   1  Ali  25.0  50000.0         HR

In [7]:
df.dropna(axis=1)

   ID Name   Age   Salary Department
0   1  Ali  25.0  50000.0         HR

In [11]:
df['Name']=df['Name'].fillna('Nodata')

In [12]:
df

   ID    Name   Age   Salary Department
0   1     Ali  25.0  50000.0         HR
1   2    John   NaN  60000.0         IT
2   3    Sara  22.0      NaN         HR
3   4  Nodata  30.0  70000.0    Finance
4   2    John   NaN  60000.0         IT
5   5   David  28.0  80000.0        NaN

In [33]:
df[["Age","Name"]]

   Age   Name
0   25    Ali
1   26   John
2   22   Sara
3   30    NaN
4   26   John
5   28  David

In [16]:
df['Age'].mean()

np.float64(26.25)

In [17]:
df['Name'].mode

<bound method Series.mode of 0       Ali
1      John
2      Sara
3    Nodata
4      John
5     David
Name: Name, dtype: str>

In [71]:
df['Age']=df['Age'].fillna(df['Age'].mean()).astype(int)

In [72]:
print(df['Age'])

0    25
1    26
2    22
3    30
4    26
5    28
Name: Age, dtype: int64

In [41]:
df['Name'].fillna(df['Name'].mode()[0])

0      Ali
1     John
2     Sara
3     John
4     John
5    David
Name: Name, dtype: str

In [42]:
df['Name'].mode()[0]

'John'

In [43]:
df.dtypes

ID              int64
Name              str
Age           float64
Salary        float64
Department        str
dtype: object

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          6 non-null      int64
 1   Name        5 non-null      str
 2   Age         4 non-null      float64
 3   Salary      5 non-null      float64
 4   Department  5 non-null      str
dtypes: float64(2), int64(1), str(2)
memory usage: 372.0 bytes

In [48]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [49]:
df

   ID   Name    Age   Salary Department
0   1    Ali  25.00  50000.0         HR
1   2   John  26.25  60000.0         IT
2   3   Sara  22.00      NaN         HR
3   4    NaN  30.00  70000.0    Finance
4   2   John  26.25  60000.0         IT
5   5  David  28.00  80000.0        NaN

In [61]:
df['Age']=df['Age'].fillna(df['Age'].mean()).astype(int)
df['Name']=df['Name'].fillna('None')

In [62]:
df

   ID   Name  Age   Salary Department
0   1    Ali   25  50000.0         HR
1   2   John   26  60000.0         IT
2   3   Sara   22      NaN         HR
3   4   none   30  70000.0    Finance
4   2   John   26  60000.0         IT
5   5  David   28  80000.0        NaN

In [67]:
df

   ID    Name   Age   Salary Department
0   1     Ali  25.0  50000.0         HR
1   2    John   NaN  60000.0         IT
2   3    Sara  22.0      NaN         HR
3   4  Nodata  30.0  70000.0    Finance
4   2    John   NaN  60000.0         IT
5   5   David  28.0  80000.0        NaN

In [68]:
df[["Age","Name"]]

    Age    Name
0  25.0     Ali
1   NaN    John
2  22.0    Sara
3  30.0  Nodata
4   NaN    John
5  28.0   David

In [69]:
df['Age'].mean()

np.float64(26.25)

In [70]:
df['Name'].mode()

0    John
Name: Name, dtype: str

In [73]:
df['Age'].fillna(df['Age'].mean())

0    25
1    26
2    22
3    30
4    26
5    28
Name: Age, dtype: int64

In [80]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df

   ID   Name    Age   Salary Department
0   1    Ali  25.00  50000.0         HR
1   2   John  26.25  60000.0         IT
2   3   Sara  22.00      NaN         HR
3   4    NaN  30.00  70000.0    Finance
4   2   John  26.25  60000.0         IT
5   5  David  28.00  80000.0        NaN

In [81]:
df['Age']=df['Age'].astype(int)

In [82]:
df

   ID   Name  Age   Salary Department
0   1    Ali   25  50000.0         HR
1   2   John   26  60000.0         IT
2   3   Sara   22      NaN         HR
3   4    NaN   30  70000.0    Finance
4   2   John   26  60000.0         IT
5   5  David   28  80000.0        NaN

In [83]:
df

   ID   Name  Age   Salary Department
0   1    Ali   25  50000.0         HR
1   2   John   26  60000.0         IT
2   3   Sara   22      NaN         HR
3   4    NaN   30  70000.0    Finance
4   2   John   26  60000.0         IT
5   5  David   28  80000.0        NaN

In [66]:
df2['Name']=df2['Name'].replace('Nodata','Manu')

In [67]:
df2

   ID   Name   Age  Monthly_Salary Department
0   1    Ali  25.0         50000.0         HR
1   2   John   NaN         60000.0         IT
2   3   Sara  22.0             NaN         HR
3   4   Manu  30.0         70000.0    Finance
5   5  David  28.0         80000.0        NaN

In [68]:
df2.duplicated()

0    False
1    False
2    False
3    False
5    False
dtype: bool

In [54]:
df2.duplicated().sum()

np.int64(0)

In [55]:
df2.drop_duplicates(inplace=True)

In [69]:
df2

   ID   Name   Age  Monthly_Salary Department
0   1    Ali  25.0         50000.0         HR
1   2   John   NaN         60000.0         IT
2   3   Sara  22.0             NaN         HR
3   4   Manu  30.0         70000.0    Finance
5   5  David  28.0         80000.0        NaN

In [70]:
df2=df2.rename(columns={"Salary":"Monthly_Salary"},)

In [71]:
df2

   ID   Name   Age  Monthly_Salary Department
0   1    Ali  25.0         50000.0         HR
1   2   John   NaN         60000.0         IT
2   3   Sara  22.0             NaN         HR
3   4   Manu  30.0         70000.0    Finance
5   5  David  28.0         80000.0        NaN

In [73]:
df2[df2["Name"].str.contains("a",case=False)]

   ID   Name   Age  Monthly_Salary Department
0   1    Ali  25.0         50000.0         HR
2   3   Sara  22.0             NaN         HR
3   4   Manu  30.0         70000.0    Finance
5   5  David  28.0         80000.0        NaN

In [75]:
df2[df2['Age']>25]

   ID   Name   Age  Monthly_Salary Department
3   4   Manu  30.0         70000.0    Finance
5   5  David  28.0         80000.0        NaN

In [76]:
df2=df[df['Department']=='IT']

In [77]:
df2

   ID  Name  Age  Monthly_Salary Department
1   2  John  NaN         60000.0         IT

In [1]:

import numpy as np
import pandas as pd

data ={
    "ID": [1,2,3,4,2,5],
    "Name":["Ali","John","Sara",None,"John","David"],
    "Age":[25,np.nan,22,30,np.nan,28],
    "Salary":[50000,60000,None,70000,60000,80000],
    "Department":["HR","IT","HR","Finance","IT",None]
}
df =pd.DataFrame(data)
df

   ID   Name   Age   Salary Department
0   1    Ali  25.0  50000.0         HR
1   2   John   NaN  60000.0         IT
2   3   Sara  22.0      NaN         HR
3   4    NaN  30.0  70000.0    Finance
4   2   John   NaN  60000.0         IT
5   5  David  28.0  80000.0        NaN

In [2]:
df['Age'].bfill()

0    25.0
1    22.0
2    22.0
3    30.0
4    28.0
5    28.0
Name: Age, dtype: float64

In [5]:
df

   ID   Name   Age   Salary Department
0   1    Ali  25.0  50000.0         HR
1   2   John   NaN  60000.0         IT
2   3   Sara  22.0      NaN         HR
3   4    NaN  30.0  70000.0    Finance
4   2   John   NaN  60000.0         IT
5   5  David  28.0  80000.0        NaN

In [4]:
df['ID'].interpolate()

0    1
1    2
2    3
3    4
4    2
5    5
Name: ID, dtype: int64

In [6]:
df['Age'].mean()

np.float64(26.25)

In [7]:
df.loc[df['Age']>120,'Age']=120

In [8]:
df

   ID   Name   Age   Salary Department
0   1    Ali  25.0  50000.0         HR
1   2   John   NaN  60000.0         IT
2   3   Sara  22.0      NaN         HR
3   4    NaN  30.0  70000.0    Finance
4   2   John   NaN  60000.0         IT
5   5  David  28.0  80000.0        NaN