In [1]:
import pandas as pd

In [2]:
data ={
    "employee":["amal","priya","rahul","sneha","ravi","anita"],
    "department":["IT","HR","IT","Finance","HR","IT"],
    "city":["bangalore","chennai","bangalore","delhi","chennai","mumbai"],
    "salary":[60000,50000,65000,70000,52000,58000,],
    "experience":[5,3,7,10,4,6]
}
df = pd.DataFrame(data)
df

  employee department       city  salary  experience
0     amal         IT  bangalore   60000           5
1    priya         HR    chennai   50000           3
2    rahul         IT  bangalore   65000           7
3    sneha    Finance      delhi   70000          10
4     ravi         HR    chennai   52000           4
5    anita         IT     mumbai   58000           6

In [3]:
df.groupby("department")

In [4]:
df.groupby("department")["salary"].mean()

department
Finance    70000.0
HR         51000.0
IT         61000.0
Name: salary, dtype: float64

In [ ]:
df.groupby("department")["salary"].sum()

department
Finance     70000
HR         102000
IT         183000
Name: salary, dtype: int64

In [6]:
df.groupby("department")["salary"].count()

department
Finance    1
HR         2
IT         3
Name: salary, dtype: int64

In [7]:
df.groupby("department")["salary"].min()

department
Finance    70000
HR         50000
IT         58000
Name: salary, dtype: int64

In [8]:
df.groupby("department")["salary"].max()

department
Finance    70000
HR         52000
IT         65000
Name: salary, dtype: int64

In [9]:
df.groupby("department")["experience"].max()

department
Finance    10
HR          4
IT          7
Name: experience, dtype: int64

In [10]:
df.groupby("department")["salary"].agg(["mean","sum","min","max"])

               mean     sum    min    max
department
Finance     70000.0   70000  70000  70000
HR          51000.0  102000  50000  52000
IT          61000.0  183000  58000  65000

In [11]:
df.groupby("department").agg({
    "salary":["mean","sum"],
    "experience":["mean","max"]
    })

             salary         experience
               mean     sum       mean max
department
Finance     70000.0   70000       10.0  10
HR          51000.0  102000        3.5   4
IT          61000.0  183000        6.0   7

In [12]:
df.groupby("department").agg(
    avg_salary=("salary","mean"),
    total_salary=("salary","sum"),
    max_experience=("experience","max")
)

            avg_salary  total_salary  max_experience
department
Finance        70000.0         70000              10
HR             51000.0        102000               4
IT             61000.0        183000               7

In [26]:
employees = pd.DataFrame({
    "EmpID":[1,2,3,4],
    "Name":["Harsha","Anamika","Aradhya","Aromal"],
    "DepID":[101,102,101,103],
    "salary":[60000,50000,65000,70000]
})
departments=pd.DataFrame({
    "DepID":[101,102,104],
    "department":["IT","HR","Finance"]
})
employees,departments

(   EmpID     Name  DepID  salary
 0      1   Harsha    101   60000
 1      2  Anamika    102   50000
 2      3  Aradhya    101   65000
 3      4   Aromal    103   70000,
    DepID department
 0    101         IT
 1    102         HR
 2    104    Finance)

In [15]:
pd.merge(employees,departments,on="DepID",how="inner")

   EmpID     Name  DepID  salary department
0      1   Harsha    101   60000         IT
1      2  Anamika    102   50000         HR
2      3  Aradhya    101   65000         IT

In [16]:
pd.merge(employees,departments,on="DepID",how="outer")

   EmpID     Name  DepID   salary department
0    1.0   Harsha    101  60000.0         IT
1    3.0  Aradhya    101  65000.0         IT
2    2.0  Anamika    102  50000.0         HR
3    4.0   Aromal    103  70000.0        NaN
4    NaN      NaN    104      NaN    Finance

In [17]:
pd.merge(employees,departments,on="DepID",how="left")

   EmpID     Name  DepID  salary department
0      1   Harsha    101   60000         IT
1      2  Anamika    102   50000         HR
2      3  Aradhya    101   65000         IT
3      4   Aromal    103   70000        NaN

In [18]:
pd.merge(employees,departments,on="DepID",how="right")

   EmpID     Name  DepID   salary department
0    1.0   Harsha    101  60000.0         IT
1    3.0  Aradhya    101  65000.0         IT
2    2.0  Anamika    102  50000.0         HR
3    NaN      NaN    104      NaN    Finance

In [19]:
pd.merge(employees,departments,on="DepID")

   EmpID     Name  DepID  salary department
0      1   Harsha    101   60000         IT
1      2  Anamika    102   50000         HR
2      3  Aradhya    101   65000         IT

In [27]:
employees.set_index("DepID",inplace=True)
departments.set_index("DepID",inplace=True)
employees.join(departments)

       EmpID     Name  salary department
DepID
101        1   Harsha   60000         IT
102        2  Anamika   50000         HR
101        3  Aradhya   65000         IT
103        4   Aromal   70000        NaN

In [22]:
employees.join(departments)

       EmpID     Name  salary  DepID department
DepID
101        1   Harsha   60000    NaN        NaN
102        2  Anamika   50000    NaN        NaN
101        3  Aradhya   65000    NaN        NaN
103        4   Aromal   70000    NaN        NaN

In [28]:
df1=employees.iloc[:2]
df2=employees.iloc[2:]
pd.concat([df1,df2])

       EmpID     Name  salary
DepID
101        1   Harsha   60000
102        2  Anamika   50000
101        3  Aradhya   65000
103        4   Aromal   70000

In [29]:
extra =pd.DataFrame({"bouns":[5000,6000,5500,7000]})
pd.concat([employees.reset_index(drop=True),extra],axis=1)

   EmpID     Name  salary  bouns
0      1   Harsha   60000   5000
1      2  Anamika   50000   6000
2      3  Aradhya   65000   5500
3      4   Aromal   70000   7000

In [32]:

pd.concat([df1,df2])

       EmpID     Name  salary
DepID
101        1   Harsha   60000
102        2  Anamika   50000
101        3  Aradhya   65000
103        4   Aromal   70000