In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in .\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import pandas  as pd

In [24]:
data={
    'name':["arjun","rohit","priya"],
    'age' :[25, 30, 22],
    'city':["delh", "mumbai", "chennai"],
}

df=pd.DataFrame(data)
print(df)

    name  age     city
0  arjun   25     delh
1  rohit   30   mumbai
2  priya   22  chennai

In [25]:
import pandas 

mydataset={
    'car' :["BMW","Volvo","ford"],
    'passings' :[3,7,2]
}
myvar= pd.DataFrame(mydataset)

In [26]:
print(myvar)

     car  passings
0    BMW         3
1  Volvo         7
2   ford         2

In [18]:
a=[1,7,2]
myvar = pd.Series(a)

In [19]:
print(myvar)

0    1
1    7
2    2
dtype: int64

In [36]:
print(df['age'].mean())

25.666666666666668

In [37]:
print(df['age'].max())

30

In [39]:
print(df['age'].min())

22

In [43]:
calories = {"day1":420,"day2":380,"day3":390}
myvar = pd.Series(calories)
print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [44]:
calories = {"day1":420,"day2":380,"day3":390}
myvar = pd.Series(calories,index=["day1","day2"])
print(myvar)

day1    420
day2    380
dtype: int64

In [45]:
data = {
    "calories" : [420,380,390],
    "duration" : [50,40,45]
}
myvar = pd.DataFrame(data)
print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45

In [46]:
data = {
    "calories" : [420,380,390],
    "duration" : [50,40,45]
}
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [49]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [51]:
print(df.loc[[0,1]])

   calories  duration
0       420        50
1       380        40

In [53]:
data = {
    "calories" : [420,380,390],
    "duration" : [50,40,45]
}
df = pd.DataFrame(data,index=["day1","day2","day3"])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [55]:
print(df.loc["day3"])

calories    390
duration     45
Name: day3, dtype: int64

In [56]:
a = [1,7,2]
myvar = pd.Series(a,index=("x","y","z"))
print(myvar)

x    1
y    7
z    2
dtype: int64

In [57]:
print(myvar["y"])

7

In [ ]:
df = pd.read_csv(3c840c46-d5fb-4e76-bf16-b2c15915f012 (1)')

SyntaxError: invalid decimal literal (1211183556.py, line 1)

In [1]:
c:\Users\Lenovo\Downloads\3c840c46-d5fb-4e76-bf16-b2c15915f012.xlsx

SyntaxError: unexpected character after line continuation character (3149846272.py, line 1)

In [2]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [64]:
import pandas as pd

In [ ]:
df=pd.read_excel(r'c:\Users\Lenovo\Downloads\car detailsss.xlsx')

C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [67]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [7]:
df.head(10)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner,19
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner,10
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner,12
8,Hyundai Creta 1.6 VTVT S,2015,850000,25000,Petrol,Individual,Manual,First Owner,11
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner,9

In [8]:
df.tail(8)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
4332,Mahindra Scorpio S2 7 Seater,2015,750000,120000,Diesel,Individual,Manual,First Owner,11
4333,Maruti Ritz VDi,2012,225000,90000,Diesel,Individual,Manual,Second Owner,14
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner,14
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [9]:
df.to_string()

'                                                            name  year  selling_price  km_driven      fuel       seller_type transmission                 owner  Age\n0                                                  Maruti 800 AC  2007          60000      70000    Petrol        Individual       Manual           First Owner   19\n1                                       Maruti Wagon R LXI Minor  2007         135000      50000    Petrol        Individual       Manual           First Owner   19\n2                                           Hyundai Verna 1.6 SX  2012         600000     100000    Diesel        Individual       Manual           First Owner   14\n3                                         Datsun RediGO T Option  2017         250000      46000    Petrol        Individual       Manual           First Owner    9\n4                                          Honda Amaze VX i-DTEC  2014         450000     141000    Diesel        Individual       Manual          Second Owner   12\n5                                           Maruti Alto LX BSIII  2007         140000     125000    Petrol        Individual       Manual           First Owner   19\n6                                      Hyundai Xcent 1.2 Kappa S  2016         550000      25000    Petrol        Individual       Manual           First Owner   10\n7                                       Tata Indigo Grand Petrol  2014         240000      60000    Petrol        Individual       Manual          Second Owner   12\n8                                       Hyundai Creta 1.6 VTVT S  2015         850000      25000    Petrol        Individual       Manual           First Owner   11\n9                                       Maruti Celerio Green VXI  2017         365000      78000       CNG        Individual       Manual           First Owner    9\n10                                       Chevrolet Sail 1.2 Base  2015         260000      35000    Petrol        Individual       Manual           First Owner   11\n11                                      Tata Indigo Grand Petrol  2014         250000     100000    Petrol        Individual       Manual           First Owner   12\n12                               Toyota Corolla Altis 1.8 VL CVT  2018        1650000      25000    Petrol            Dealer    Automatic           First Owner    8\n13                                                 Maruti 800 AC  2007          60000      70000    Petrol        Individual       Manual           First Owner   19\n14                                      Maruti Wagon R LXI Minor  2007         135000      50000    Petrol        Individual       Manual           First Owner   19\n15                                          Hyundai Verna 1.6 SX  2012         600000     100000    Diesel        Individual       Manual           First Owner   14\n16                                        Datsun RediGO T Option  2017         250000      46000    Petrol        Individual       Manual           First Owner    9\n17                                         Honda Amaze VX i-DTEC  2014         450000     141000    Diesel        Individual       Manual          Second Owner   12\n18                                          Maruti Alto LX BSIII  2007         140000     125000    Petrol        Individual       Manual           First Owner   19\n19                                     Hyundai Xcent 1.2 Kappa S  2016         550000      25000    Petrol        Individual       Manual           First Owner   10\n20                                      Tata Indigo Grand Petrol  2014         240000      60000    Petrol        Individual       Manual          Second Owner   12\n21                                      Hyundai Creta 1.6 VTVT S  2015         850000      25000    Petrol        Individual       Manual           First Owner   11\n22                                      Maruti Celerio Green VXI  2017         365000      78000       CNG        Individual       Manual           First Owner    9\n23                                       Chevrolet Sail 1.2 Base  2015         260000      35000    Petrol        Individual       Manual           First Owner   11\n24                                      Tata Indigo Grand Petrol  2014         250000     100000    Petrol        Individual       Manual           First Owner   12\n25                               Toyota Corolla Altis 1.8 VL CVT  2018        1650000      25000    Petrol            Dealer    Automatic           First Owner    8\n26                                          Maruti Ciaz VXi Plus  2015         585000      24000    Petrol            Dealer       Manual           First Owner   11\n27                                   Hyundai Venue SX Opt Diesel  2019        1195000       5000    Diesel            Dealer       Manual           First Owner    7\n28                             Chevrolet Enjoy TCDi LTZ 7 Seater  2013         390000      33000    Diesel        Individual       Manual          Second Owner   13\n29                                    Jaguar XF 2.2 Litre Luxury  2014        1964999      28000    Diesel            Dealer    Automatic           First Owner   12\n30                          Mercedes-Benz New C-Class 220 CDI AT  2013        1425000      59000    Diesel            Dealer    Automatic           First Owner   13\n31                             Maruti Vitara Brezza ZDi Plus AMT  2018         975000       4500    Diesel            Dealer    Automatic           First Owner    8\n32                                               Audi Q5 2.0 TDI  2011        1190000     175900    Diesel            Dealer    Automatic           First Owner   15\n33                                               Honda City V MT  2018         930000      14500    Petrol            Dealer       Manual           First Owner    8\n34                                    Tata Tigor 1.2 Revotron XT  2018         525000      15000    Petrol        Individual       Manual           First Owner    8\n35                               Audi A6 2.0 TDI  Design Edition  2013        1735000      50000    Diesel            Dealer    Automatic           First Owner   13\n36                Mercedes-Benz New C-Class C 220 CDI Avantgarde  2012        1375000      33800    Diesel            Dealer    Automatic          Second Owner   14\n37                           Skoda Superb Ambition 2.0 TDI CR AT  2011         450000     130400    Diesel            Dealer    Automatic          Second Owner   15\n38                                     Toyota Corolla Altis G AT  2016         900000      50000    Petrol        Individual    Automatic           First Owner   10\n39                         Toyota Innova 2.5 G (Diesel) 7 Seater  2015        1300000      80000    Diesel        Individual       Manual           First Owner   11\n40                              Jeep Compass 1.4 Sport Plus BSIV  2019        1400000      10000    Petrol        Individual       Manual           First Owner    7\n41                      Mercedes-Benz E-Class E 200 CGI Elegance  2010         850000     119000    Petrol            Dealer    Automatic           First Owner   16\n42                                        Hyundai i10 Magna 1.1L  2014         229999      60000    Petrol        Individual       Manual  Fourth & Above Owner   12\n43                                  BMW 3 Series 320d Sport Line  2013        1550000      75800    Diesel            Dealer    Automatic          Second Owner   13\n44                                Audi Q7 35 TDI Quattro Premium  2009        1250000      78000    Diesel            Dealer    Automatic           Third Owner   17\n45                                        Hyundai Elantra CRDi S  2012         625000      40000    Diesel        Individual       Manual           First Owner   14\n46                                     Mahindra Scorpio 1.99 S10  2014        1050000      50000    Diesel        Individual       Manual           First Owner   12\n47                                           Honda City i DTEC V  2014         560000      74000    Diesel        Individual       Manual          Second Owner   12\n48                             Maruti Wagon R VXI BS IV with ABS  2014         290000      64000    Petrol        Individual       Manual          Second Owner   12\n49                                      Maruti Wagon R VXI BS IV  2012         275000      60000    Petrol        Individual       Manual          Second Owner   14\n50                                           Mahindra Scorpio LX  2009         411000     120000    Diesel        Individual       Manual          Second Owner   17\n51                                       Hyundai Santro Xing GLS  2009         150000      79000    Petrol        Individual       Manual           Third Owner   17\n52                              Hyundai Grand i10 1.2 Kappa Asta  2019         500000      15000    Petrol        Individual       Manual           First Owner    7\n53                                               Maruti Alto LXi  2006         100000      80000    Petrol        Individual       Manual           First Owner   20\n54                               Maruti Swift Dzire VDI Optional  2017         725000      18500    Diesel            Dealer       Manual           First Owner    9\n55                                  Maruti Eeco 5 Seater AC BSIV  2018         401000      10200    Petrol            Dealer       Manual           First Owner    8\n56                                   Hyundai i20 Sportz 1.4 CRDi  2018         750000      29000    Diesel            Dealer       Manual           First Owner    8\n57    Maruti Omni Maruti Omni MPI STD BSIII 5-STR W/ IMMOBILISER  2018         310000      28000    Petrol            Dealer       Manual           First Owner    8\n58                                         Maruti Swift ZDi BSIV  2016         665000      46000    Diesel            Dealer       Manual           First Owner   10\n59                  Hyundai i20 2015-2017 Sportz Option 1.4 CRDi  2014         465000      70000    Diesel            Dealer       Manual           First Owner   12\n60                                               Maruti Alto LXi  2012         160000      60000    Petrol        Individual       Manual          Second Owner   14\n61                                      Mahindra Jeep CL 500 MDI  1996         250000      35000    Diesel        Individual       Manual          Second Owner   30\n62                                          Honda City i DTEC VX  2014         675000      90000    Diesel            Dealer       Manual           First Owner   12\n63                                      Maruti Wagon R VXI BS IV  2013         300000      80000    Petrol            Dealer       Manual           First Owner   13\n64                                               Tata Indica DLS  2005          70000      80000    Diesel        Individual       Manual           First Owner   21\n65                                        Hyundai EON Magna Plus  2014         240000      73300    Petrol            Dealer       Manual          Second Owner   12\n66                                               Toyota Etios GD  2014         525000      92000    Diesel            Dealer       Manual           First Owner   12\n67                                               Maruti Alto LXi  2009         151000      66764    Petrol            Dealer       Manual          Second Owner   17\n68                                               Maruti Alto LXi  2009         140000     100000    Petrol        Individual       Manual           First Owner   17\n69                 Chevrolet Tavera Neo LS B3 - 7(C) seats BSIII  2010         280000     350000    Diesel        Individual       Manual          Second Owner   16\n70                              Toyota Corolla Altis Diesel D4DG  2011         350000     230000    Diesel        Individual       Manual           First Owner   15\n71                                 Mahindra Scorpio 1.99 S6 Plus  2017         570000      60000    Diesel        Individual       Manual           First Owner    9\n72                                        Hyundai EON Magna Plus  2018         300000      31000    Petrol        Individual       Manual           First Owner    8\n73                                     Tata Indigo Classic Dicor  2007         100000      39000    Diesel        Individual       Manual           First Owner   19\n74                           Toyota Innova 2.5 V Diesel 8-seater  2009         500000     120000    Diesel        Individual       Manual           Third Owner   17\n75                                Tata Indica Vista Quadrajet LS  2014         125000     166000    Diesel        Individual       Manual  Fourth & Above Owner   12\n76                                          Maruti Swift 1.3 VXi  2006         130000     110000    Petrol        Individual       Manual           Third Owner   20\n77                        Ford EcoSport 1.5 Diesel Titanium BSIV  2017         925000      35000    Diesel        Individual       Manual           First Owner    9\n78                                         Maruti Ciaz 1.3 Delta  2018         750000      60000    Diesel        Individual       Manual           First Owner    8\n79                                          Honda Civic 1.8 V AT  2007         200000      54000    Petrol        Individual    Automatic          Second Owner   19\n80                                        Hyundai i10 Sportz 1.2  2010         248000      63000    Petrol        Individual       Manual          Second Owner   16\n81                                  Skoda Rapid 1.5 TDI Elegance  2014         450000     120000    Diesel        Individual       Manual          Second Owner   12\n82                                              Hyundai Getz GLS  2005          80000     120000    Petrol        Individual       Manual           Third Owner   21\n83                                             Nissan Terrano XL  2014         650000      76000    Petrol        Individual       Manual          Second Owner   12\n84                                 Hyundai Grand i10 CRDi Sportz  2015         450000      80000    Diesel        Individual       Manual           First Owner   11\n85                                  Hyundai Elite i20 Diesel Era  2019         650000      25000    Diesel        Individual       Manual           First Owner    7\n86                                          Honda Amaze S i-VTEC  2016         495000      11958    Petrol            Dealer       Manual           First Owner   10\n87                                               Honda Brio S MT  2015         371000      20000    Petrol            Dealer       Manual           First Owner   11\n88                                   Hyundai Creta 1.6 SX Option  2017        1025000       9000    Petrol            Dealer       Manual           First Owner    9\n89             Mercedes-Benz S-Class S 350d Connoisseurs Edition  2017        8150000       6500    Diesel            Dealer    Automatic           First Owner    9\n90                                        Mahindra XUV500 W8 2WD  2015         750000      70000    Diesel        Individual       Manual           First Owner   11\n91                       Renault Duster 85PS Diesel RxL Optional  2013         600000     120000    Diesel        Individual       Manual           First Owner   13\n92                                        Hyundai Santro Xing XO  2007          80000      58000    Petrol            Dealer       Manual          Second Owner   19\n93                                 Mahindra Bolero 2011-2019 SLE  2013         325000      62200    Diesel            Dealer       Manual           First Owner   13\n94                                  Audi A6 2.0 TDI Premium Plus  2014        1470000      34000    Diesel            Dealer    Automatic          Second Owner   12\n95                               Fiat Avventura MULTIJET Emotion  2015         350000      53000    Diesel        Individual       Manual          Second Owner   11\n96                                               Audi A8 4.2 TDI  2013        2800000      49000    Diesel            Dealer    Automatic           First Owner   13\n97                                           Datsun RediGO 1.0 S  2017         210000      15000    Petrol            Dealer       Manual          Second Owner    9\n98                          Volkswagen Jetta 1.4 TSI Comfortline  2013         450000      50000    Petrol        Individual       Manual           First Owner   13\n99                          Audi A4 2.0 TDI 177 Bhp Premium Plus  2013        1150000      53000    Diesel            Dealer    Automatic           First Owner   13\n100                                         Honda Civic 1.8 V AT  2009         210000      63500    Petrol            Dealer    Automatic           First Owner   17\n101                   Mercedes-Benz E-Class Exclusive E 200 BSIV  2018        4500000       9800    Petrol            Dealer    Automatic           First Owner    8\n102                                      BMW X1 sDrive 20d xLine  2017        2750000      13000    Diesel        Individual    Automatic           First Owner    9\n103                                        Volvo V40 D3 R Design  2018        1975000      21000    Diesel            Dealer    Automatic           First Owner    8\n104                                         Maruti SX4 Zxi BSIII  2008         175000      29173    Petrol            Dealer       Manual           First Owner   18\n105                                           BMW 7 Series 730Ld  2012        2500000      48000    Diesel            Dealer    Automatic           First Owner   14\n106                               Mahindra Bolero Power Plus SLX  2017         628000     120000    Diesel        Individual       Manual           First Owner    9\n107                                      Hyundai Sonata CRDi M/T  2010         600000     100000    Diesel        Individual       Manual           First Owner   16\n108                                Nissan Micra Active XV Petrol  2017         399000      30000    Petrol        Individual       Manual           First Owner    9\n109                                             Mahindra Xylo D4  2018         750000      87000    Diesel        Individual       Manual           First Owner    8\n110                 Hyundai Elite i20 Sportz Plus Dual Tone BSIV  2019         750000      15000    Petrol        Individual       Manual           First Owner    7\n111                                             Renault KWID RXT  2017         315000      16000    Petrol        Individual       Manual           First Owner    9\n112                                      Mahindra Xylo E4 BS III  2012         600000      60000    Diesel        Individual       Manual           First Owner   14\n113                                     Maruti Wagon R LXI Minor  2010         100000      60000    Petrol        Individual       Manual  Fourth & Above Owner   16\n114                                       Maruti SX4 ZXI MT BSIV  2011         250000     110000    Petrol        Individual       Manual           Third Owner   15\n115                                             Renault KWID RXT  2017         350000      25000    Petrol        Individual       Manual           First Owner    9\n116                                     Hyundai Creta 1.4 CRDi S  2016         780000      60000    Diesel        Individual       Manual           First Owner   10\n117                                       Maruti Swift Dzire VDI  2014         434000      79350    Diesel        Individual       Manual          Second Owner   12\n118                           Hyundai Verna 1.6 VTVT AT S Option  2016         690000      80000    Petrol        Individual    Automatic           First Owner   10\n119                                     Mahindra Scorpio LX BSIV  2014         

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   str
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   str
 5   seller_type    4340 non-null   str
 6   transmission   4340 non-null   str
 7   owner          4340 non-null   str
 8   Age            4340 non-null   int64
dtypes: int64(4), str(5)
memory usage: 305.3 KB

In [11]:
df.describe()

              year  selling_price      km_driven          Age
count  4340.000000   4.340000e+03    4340.000000  4340.000000
mean   2013.090783   5.041273e+05   66215.777419    12.909217
std       4.215344   5.785487e+05   46644.102194     4.215344
min    1992.000000   2.000000e+04       1.000000     6.000000
25%    2011.000000   2.087498e+05   35000.000000    10.000000
50%    2014.000000   3.500000e+05   60000.000000    12.000000
75%    2016.000000   6.000000e+05   90000.000000    15.000000
max    2020.000000   8.900000e+06  806599.000000    34.000000

In [18]:
df["new_selling_price"]=df["selling_price"]+df["km_driven"]

In [19]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age,new_selling_price
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19,130000
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19,185000
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14,700000
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9,296000
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12,591000
...,...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12,489999
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12,489999
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17,193000
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10,955000
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10,265000

In [20]:
df=df.drop("new_selling_price",axis=1)

In [21]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [22]:
df2=df[df["year"]>2010]

In [24]:
df2

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner,10
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner,14
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [34]:
df3=df[df["fuel"]=="Diesel"]

In [35]:
df3

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
15,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
17,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
27,Hyundai Venue SX Opt Diesel,2019,1195000,5000,Diesel,Dealer,Manual,First Owner,7
...,...,...,...,...,...,...,...,...,...
4333,Maruti Ritz VDi,2012,225000,90000,Diesel,Individual,Manual,Second Owner,14
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner,14
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10

In [36]:
df2.sort_values("selling_price",inplace=True)

In [37]:
df2

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
1832,Tata Nano LX SE,2012,35000,35000,Petrol,Individual,Manual,Third Owner,14
877,Tata Nano Std,2011,40000,19000,Petrol,Individual,Manual,First Owner,15
1468,Tata Nano Cx BSIII,2014,45000,7000,Petrol,Individual,Manual,Second Owner,12
3087,Tata Nano Lx BSIV,2012,45000,35000,Petrol,Individual,Manual,Second Owner,14
4158,Tata Nano Cx BSIII,2014,45000,7000,Petrol,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
2239,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,7
2258,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,7
3969,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016,5500000,77350,Diesel,Dealer,Automatic,First Owner,10
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,8150000,6500,Diesel,Dealer,Automatic,First Owner,9
3872,Audi RS7 2015-2019 Sportback Performance,2016,8900000,13000,Petrol,Dealer,Automatic,First Owner,10

In [68]:
import pandas as pd

In [95]:
df5=pd.read_excel(r'c:\Users\Lenovo\Downloads\car detailsss.xlsx',header=None)

In [72]:
df5

,0,1,2,3,4,5,6,7,8
0,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
1,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
2,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
3,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
4,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
...,...,...,...,...,...,...,...,...,...
4336,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4338,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4339,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4340,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [96]:
df5=pd.read_excel(r'c:\Users\Lenovo\Downloads\car detailsss.xlsx',usecols=["name","year"])

C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [75]:
df5

                                     name  year
0                           Maruti 800 AC  2007
1                Maruti Wagon R LXI Minor  2007
2                    Hyundai Verna 1.6 SX  2012
3                  Datsun RediGO T Option  2017
4                   Honda Amaze VX i-DTEC  2014
...                                   ...   ...
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014
4336           Hyundai i20 Magna 1.4 CRDi  2014
4337                  Maruti 800 AC BSIII  2009
4338     Hyundai Creta 1.6 CRDi SX Option  2016
4339                     Renault KWID RXT  2016

[4340 rows x 2 columns]

In [109]:
import pandas as pd

In [110]:
df5=pd.read_excel(r'c:\Users\Lenovo\Downloads\car detailsss.xlsx',names=["index","num","name","year","km","fuel","company"])

C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [111]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [112]:
df.loc[0:3]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9