In [20]:
import pandas as pd

data={
    "Customer":["Amit","PRIYA","rahul","Amit"],
    "Email":["amit@gmail.com","priya@company.org","rahul123@yahoo.com","sneha@GMAIL.com"],
    "Phone":["+91-9876543210","987643211","91-9876543212","9876543213"],
    "Amount":["$1,200","1500 INR","Rs.2,000","1500"]
}
df=pd.DataFrame(data)
df

  Customer               Email           Phone    Amount
0     Amit      amit@gmail.com  +91-9876543210    $1,200
1    PRIYA   priya@company.org       987643211  1500 INR
2    rahul  rahul123@yahoo.com   91-9876543212  Rs.2,000
3     Amit     sneha@GMAIL.com      9876543213      1500

In [9]:

df["Customer"]=df["Customer"].str.strip()
df

  Customer               Email           Phone    Amount
0     Amit      amit@gmail.com  +91-9876543210    $1,200
1    PRIYA   priya@company.org       987643211  1500 INR
2    rahul  rahul123@yahoo.com   91-9876543212  Rs.2,000
3     Amit     sneha@GMAIL.com      9876543213      1500

In [10]:
df["Customer"]=df["Customer"].str.lower()
df

  Customer               Email           Phone    Amount
0     amit      amit@gmail.com  +91-9876543210    $1,200
1    priya   priya@company.org       987643211  1500 INR
2    rahul  rahul123@yahoo.com   91-9876543212  Rs.2,000
3     amit     sneha@GMAIL.com      9876543213      1500

In [12]:
df["Amount"]=df["Amount"].str.replace(",","")
df

  Customer               Email           Phone    Amount
0     amit      amit@gmail.com  +91-9876543210     $1200
1    priya   priya@company.org       987643211  1500 INR
2    rahul  rahul123@yahoo.com   91-9876543212   Rs.2000
3     amit     sneha@GMAIL.com      9876543213      1500

In [13]:
df["Amount"]=df["Amount"].str.replace("Rs.","")
df

  Customer               Email           Phone    Amount
0     amit      amit@gmail.com  +91-9876543210     $1200
1    priya   priya@company.org       987643211  1500 INR
2    rahul  rahul123@yahoo.com   91-9876543212      2000
3     amit     sneha@GMAIL.com      9876543213      1500

In [23]:
df["Amount"]=df["Amount"].str.replace(r"[$INR .-]","",regex=True)
df

  Customer               Email         Phone  Amount
0     Amit      amit@gmail.com  +-9876543210   1,200
1    PRIYA   priya@company.org     987643211    1500
2    rahul  rahul123@yahoo.com   -9876543212  s2,000
3     Amit     sneha@GMAIL.com    9876543213    1500

In [24]:
df["Phone"]=df["Phone"].str.replace("91","")
df

  Customer               Email         Phone  Amount
0     Amit      amit@gmail.com  +-9876543210   1,200
1    PRIYA   priya@company.org     987643211    1500
2    rahul  rahul123@yahoo.com   -9876543212  s2,000
3     Amit     sneha@GMAIL.com    9876543213    1500

In [25]:
df["Phone"]=df["Phone"].str.replace("+","")
df

  Customer               Email        Phone  Amount
0     Amit      amit@gmail.com  -9876543210   1,200
1    PRIYA   priya@company.org    987643211    1500
2    rahul  rahul123@yahoo.com  -9876543212  s2,000
3     Amit     sneha@GMAIL.com   9876543213    1500

In [26]:
df["Phone"]=df["Phone"].str.replace("-","")
df

  Customer               Email       Phone  Amount
0     Amit      amit@gmail.com  9876543210   1,200
1    PRIYA   priya@company.org   987643211    1500
2    rahul  rahul123@yahoo.com  9876543212  s2,000
3     Amit     sneha@GMAIL.com  9876543213    1500

In [32]:
import pandas as pd

data={
    "Customer":["Amit","PRIYA","rahul","Amit"],
    "Email":["amit@gmail.com","priya@company.org","rahul123@yahoo.com","sneha@GMAIL.com"],
    "Phone":["+91-9876543210","987643211","91-9876543212","9876543213"],
    "Amount":["$1,200","1500 INR","Rs.2,000","1500"]
}
df=pd.DataFrame(data)
df

  Customer               Email           Phone    Amount
0     Amit      amit@gmail.com  +91-9876543210    $1,200
1    PRIYA   priya@company.org       987643211  1500 INR
2    rahul  rahul123@yahoo.com   91-9876543212  Rs.2,000
3     Amit     sneha@GMAIL.com      9876543213      1500

In [33]:
df["Amount"]=df["Amount"].str.replace(r"[^\d \s]","", regex=True)
df

  Customer               Email           Phone Amount
0     Amit      amit@gmail.com  +91-9876543210   1200
1    PRIYA   priya@company.org       987643211  1500
2    rahul  rahul123@yahoo.com   91-9876543212   2000
3     Amit     sneha@GMAIL.com      9876543213   1500

In [36]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Collecting matplotlib
  Using cached matplotlib-3.11.2-cp313-cp313-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.4.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Using cached fonttools-4.67.0-cp313-cp313-win_amd64.whl.metadata (139 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.1-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.5.4)
Requirement already satisfied: packaging>=20.0 in C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Using cached pillow-13.0.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Using cached matplotlib-3.11.2-cp313-cp313-win_amd64.whl (9.3 MB)
Using cached contourpy-1.4.0-cp313-cp313-win_amd64.whl (234 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.67.0-cp313-cp313-win_amd64.whl (2.5 MB)
Using cached kiwisolver-1.5.1-cp313-cp313-win_amd64.whl (70 kB)
Downloading pillow-13.0.0-cp313-cp313-win_amd64.whl (7.3 MB)
   ---------------------------------------- 0.0/7.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.3 MB ? eta -:--:--
   ------- -------------------------------- 1.3/7.3 MB 7.4 MB/s eta 0:00:01
   -------------------- ------------------- 3.7/7.3 MB 9.6 MB/s eta 0:00:01
   ----------------------------------- ---- 6.6/7.3 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------- 7.3/7.3 MB 10.0 MB/s  0:00:00
Using cached pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Lenovo\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\PIL\\FtexImagePlugin.py'
Check the permissions.


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip